import { GenreOption } from '../types/book';

export const GENRES: GenreOption[] = [
  // Fiction
  { id: 'f1', name: 'Action and adventure', category: 'Fiction' },
  { id: 'f2', name: 'Alternate history', category: 'Fiction' },
  { id: 'f3', name: 'Anthology', category: 'Fiction' },
  { id: 'f4', name: 'Chick lit', category: 'Fiction' },
  { id: 'f5', name: 'Children\'s', category: 'Fiction' },
  { id: 'f6', name: 'Classic', category: 'Fiction' },
  { id: 'f7', name: 'Comic book', category: 'Fiction' },
  { id: 'f8', name: 'Coming-of-age', category: 'Fiction' },
  { id: 'f9', name: 'Crime', category: 'Fiction' },
  { id: 'f10', name: 'Drama', category: 'Fiction' },
  { id: 'f11', name: 'Fairytale', category: 'Fiction' },
  { id: 'f12', name: 'Fantasy', category: 'Fiction' },
  { id: 'f13', name: 'Graphic novel', category: 'Fiction' },
  { id: 'f14', name: 'Historical fiction', category: 'Fiction' },
  { id: 'f15', name: 'Horror', category: 'Fiction' },
  { id: 'f16', name: 'Mystery', category: 'Fiction' },
  { id: 'f17', name: 'Paranormal romance', category: 'Fiction' },
  { id: 'f18', name: 'Picture book', category: 'Fiction' },
  { id: 'f19', name: 'Poetry', category: 'Fiction' },
  { id: 'f20', name: 'Political thriller', category: 'Fiction' },
  { id: 'f21', name: 'Romance', category: 'Fiction' },
  { id: 'f22', name: 'Satire', category: 'Fiction' },
  { id: 'f23', name: 'Science fiction', category: 'Fiction' },
  { id: 'f24', name: 'Short story', category: 'Fiction' },
  { id: 'f25', name: 'Suspense', category: 'Fiction' },
  { id: 'f26', name: 'Thriller', category: 'Fiction' },
  { id: 'f27', name: 'Western', category: 'Fiction' },
  { id: 'f28', name: 'Young adult', category: 'Fiction' },

  // Nonfiction
  { id: 'nf1', name: 'Art/architecture', category: 'Nonfiction' },
  { id: 'nf2', name: 'Autobiography', category: 'Nonfiction' },
  { id: 'nf3', name: 'Biography', category: 'Nonfiction' },
  { id: 'nf4', name: 'Business/economics', category: 'Nonfiction' },
  { id: 'nf5', name: 'Crafts/hobbies', category: 'Nonfiction' },
  { id: 'nf6', name: 'Cookbook', category: 'Nonfiction' },
  { id: 'nf7', name: 'Diary', category: 'Nonfiction' },
  { id: 'nf8', name: 'Dictionary', category: 'Nonfiction' },
  { id: 'nf9', name: 'Encyclopedia', category: 'Nonfiction' },
  { id: 'nf10', name: 'Guide', category: 'Nonfiction' },
  { id: 'nf11', name: 'Health/fitness', category: 'Nonfiction' },
  { id: 'nf12', name: 'History', category: 'Nonfiction' },
  { id: 'nf13', name: 'Home and garden', category: 'Nonfiction' },
  { id: 'nf14', name: 'Humor', category: 'Nonfiction' },
  { id: 'nf15', name: 'Journal', category: 'Nonfiction' },
  { id: 'nf16', name: 'Math', category: 'Nonfiction' },
  { id: 'nf17', name: 'Memoir', category: 'Nonfiction' },
  { id: 'nf18', name: 'Philosophy', category: 'Nonfiction' },
  { id: 'nf19', name: 'Prayer', category: 'Nonfiction' },
  { id: 'nf20', name: 'Religion, spirituality, and new age', category: 'Nonfiction' },
  { id: 'nf21', name: 'Textbook', category: 'Nonfiction' },
  { id: 'nf22', name: 'True crime', category: 'Nonfiction' },
  { id: 'nf23', name: 'Review', category: 'Nonfiction' },
  { id: 'nf24', name: 'Science', category: 'Nonfiction' },
  { id: 'nf25', name: 'Self help', category: 'Nonfiction' },
  { id: 'nf26', name: 'Sports and leisure', category: 'Nonfiction' },
  { id: 'nf27', name: 'Travel', category: 'Nonfiction' },
];
